'use client';

import React, { useState, useEffect } from 'react';
import Link from 'next/link';
import { Users, DollarSign, Wallet, Activity, RefreshCw, FileText, Loader2 } from 'lucide-react';
import jsPDF from 'jspdf';
import 'jspdf-autotable';

export default function AdminDashboard() {
  const [stats, setStats] = useState(null);
  const [isLoading, setIsLoading] = useState(true);
  const [error, setError] = useState(null);
  const [isPdfGenerating, setIsPdfGenerating] = useState(false);

  const fetchStats = async () => {
    setIsLoading(true);
    setError(null);
    try {
      const res = await fetch('/api/admin/stats');
      const data = await res.json();
      if (res.ok && data.success) {
        setStats(data.stats);
      } else {
        throw new Error(data.error || 'Failed to fetch stats');
      }
    } catch (err) {
      setError(err.message);
    } finally {
      setIsLoading(false);
    }
  };

  useEffect(() => {
    fetchStats();
  }, []);

  const generatePDFReport = async () => {
    if (!stats) return;
    setIsPdfGenerating(true);
    
    try {
      // Create new PDF document
      const doc = new jsPDF();
      
      // Document Settings
      const pageWidth = doc.internal.pageSize.width;
      
      // Header - Brand Name
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(24);
      doc.setTextColor(6, 182, 212); // Cyan 500
      doc.text('Pika', 14, 22);
      doc.setTextColor(30, 41, 59); // Slate 800
      doc.text('Earn', 28, 22);
      
      // Subtitle
      doc.setFontSize(12);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(100, 116, 139); // Slate 500
      doc.text('Admin Control Center - System Report', 14, 30);
      
      // Report Meta Data (Right Aligned)
      doc.setFontSize(10);
      const dateStr = `Date: ${new Date().toLocaleDateString()} ${new Date().toLocaleTimeString()}`;
      doc.text(dateStr, pageWidth - 14, 22, { align: 'right' });
      doc.text('Generated by: System Administrator', pageWidth - 14, 28, { align: 'right' });
      
      // Divider Line
      doc.setDrawColor(226, 232, 240); // Slate 200
      doc.setLineWidth(0.5);
      doc.line(14, 35, pageWidth - 14, 35);
      
      // Section: Overview Statistics
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(14);
      doc.setTextColor(15, 23, 42); // Slate 900
      doc.text('System Overview', 14, 48);

      // We'll fetch top users to add to the report for a fuller data display
      const usersRes = await fetch('/api/admin/users');
      const usersData = await usersRes.json();
      const topUsers = usersData.success ? usersData.users.slice(0, 10) : []; // Top 10 latest

      // Stats Table
      doc.autoTable({
        startY: 54,
        head: [['Metric', 'Value']],
        body: [
          ['Total Registered Users', stats.totalUsers.toString()],
          ['Total System Earnings (Generated)', `$${stats.totalEarned.toFixed(2)}`],
          ['Total User Balances (Owed)', `$${stats.totalBalance.toFixed(2)}`],
          ['Pending Withdrawal Requests', stats.pendingWithdrawals.toString()]
        ],
        theme: 'grid',
        headStyles: { fillColor: [6, 182, 212], textColor: [255, 255, 255] }, // Cyan
        styles: { fontSize: 11, cellPadding: 6 },
        columnStyles: {
          0: { fontStyle: 'bold', cellWidth: 100 },
          1: { cellWidth: 'auto' }
        }
      });

      // Section: Recent Users
      const finalY = doc.lastAutoTable.finalY || 100;
      
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(14);
      doc.setTextColor(15, 23, 42);
      doc.text('Recent User Activity (Top 10)', 14, finalY + 15);

      const tableData = topUsers.map(u => [
        u.id.toString(),
        u.username || 'Unknown',
        `$${Number(u.balance).toFixed(2)}`,
        `$${Number(u.total_earned).toFixed(2)}`,
        new Date(u.created_at).toLocaleDateString()
      ]);

      doc.autoTable({
        startY: finalY + 22,
        head: [['User ID', 'Username', 'Balance', 'Total Earned', 'Joined']],
        body: tableData,
        theme: 'striped',
        headStyles: { fillColor: [30, 41, 59] }, // Slate 800
        styles: { fontSize: 9 },
      });

      // Footer
      const pageCount = doc.internal.getNumberOfPages();
      for (let i = 1; i <= pageCount; i++) {
        doc.setPage(i);
        doc.setFont('helvetica', 'normal');
        doc.setFontSize(8);
        doc.setTextColor(148, 163, 184); // Slate 400
        doc.text(
          `Page ${i} of ${pageCount} - PikaEarn Confidential`,
          pageWidth / 2,
          doc.internal.pageSize.height - 10,
          { align: 'center' }
        );
      }
      
      // Save
      doc.save(`PikaEarn_Report_${new Date().toISOString().split('T')[0]}.pdf`);
      
    } catch (err) {
      console.error('PDF Generation Error:', err);
      alert('Failed to generate PDF. Please try again.');
    } finally {
      setIsPdfGenerating(false);
    }
  };

  const statCards = [
    { title: 'Total Users', value: stats?.totalUsers || 0, icon: Users, color: 'text-blue-400', bg: 'bg-blue-400/10', link: '/admin/users' },
    { title: 'Total Payouts Pending', value: stats?.pendingWithdrawals || 0, icon: Activity, color: 'text-amber-400', bg: 'bg-amber-400/10', link: '/admin/withdrawals' },
    { title: 'Total User Balances', value: `$${(stats?.totalBalance || 0).toFixed(2)}`, icon: Wallet, color: 'text-emerald-400', bg: 'bg-emerald-400/10', link: '/admin/users' },
    { title: 'Total System Earnings', value: `$${(stats?.totalEarned || 0).toFixed(2)}`, icon: DollarSign, color: 'text-cyan-400', bg: 'bg-cyan-400/10', link: '/admin/users' },
  ];

  return (
    <div className="space-y-6">
      <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4">
        <div>
          <h1 className="text-2xl font-bold text-white">Dashboard Overview</h1>
          <p className="text-slate-400 text-sm mt-1">Real-time statistics and system metrics</p>
        </div>
        
        <div className="flex items-center space-x-3 w-full sm:w-auto">
          <button 
            onClick={fetchStats}
            disabled={isLoading}
            className="p-2 bg-slate-800 hover:bg-slate-700 text-slate-300 rounded-lg transition-colors border border-slate-700 disabled:opacity-50"
            title="Refresh Stats"
          >
            <RefreshCw className={`w-5 h-5 ${isLoading ? 'animate-spin text-cyan-400' : ''}`} />
          </button>
          
          <button 
            onClick={generatePDFReport}
            disabled={isLoading || !stats || isPdfGenerating}
            className="flex-1 sm:flex-none flex items-center justify-center space-x-2 px-4 py-2 bg-cyan-500/10 hover:bg-cyan-500/20 text-cyan-400 border border-cyan-500/20 rounded-lg transition-all font-semibold text-sm disabled:opacity-50"
          >
            {isPdfGenerating ? <Loader2 className="w-4 h-4 animate-spin" /> : <FileText className="w-4 h-4" />}
            <span>Generate PDF</span>
          </button>
        </div>
      </div>

      {error && (
        <div className="bg-red-950/50 border border-red-900/50 text-red-400 p-4 rounded-xl text-sm">
          {error}
        </div>
      )}

      {/* Grid changed to ensure perfect mobile responsiveness and wrapped cards in Link */}
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4 sm:gap-6">
        {statCards.map((card, idx) => {
          const Icon = card.icon;
          return (
            <Link href={card.link} key={idx} className="block group">
              <div className="bg-slate-900 border border-slate-800 rounded-2xl p-6 relative overflow-hidden group-hover:border-cyan-500/50 group-hover:bg-slate-800/80 transition-all shadow-sm hover:shadow-cyan-900/20 hover:-translate-y-1 duration-300 h-full">
                <div className="flex justify-between items-start">
                  <div>
                    <p className="text-slate-400 text-xs sm:text-sm font-semibold uppercase tracking-wider mb-1">{card.title}</p>
                    <h3 className="text-2xl sm:text-3xl font-black text-white">
                      {isLoading ? <span className="animate-pulse bg-slate-800 h-8 w-16 rounded block mt-2"></span> : card.value}
                    </h3>
                  </div>
                  <div className={`p-3 rounded-xl ${card.bg}`}>
                    <Icon className={`w-5 h-5 sm:w-6 sm:h-6 ${card.color}`} />
                  </div>
                </div>
                <div className="absolute -bottom-6 -right-6 opacity-5 group-hover:opacity-10 transition-opacity transform group-hover:scale-110 duration-500">
                  <Icon className="w-24 h-24 sm:w-32 sm:h-32" />
                </div>
              </div>
            </Link>
          );
        })}
      </div>
    </div>
  );
}
